apiVersion: v2
name: api
description: Umbrella chart for HyperFleet API deployment
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: hyperfleet-api
    version: "1.0.0"
    repository: "git+https://github.com/openshift-hyperfleet/hyperfleet-api@charts?ref=main"
