apiVersion: v2
name: adapter1
description: Sample cluster adapter 1 using HyperFleet adapter framework
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: hyperfleet-adapter
    version: "1.0.0"
    repository: "git+https://github.com/openshift-hyperfleet/hyperfleet-adapter@charts?ref=main"
