apiVersion: v2
name: maestro-stack
description: Umbrella chart for Maestro Server and Agent deployment
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: maestro-server
    version: "0.1.0"
    repository: "git+https://github.com/openshift-online/maestro@charts/maestro-server?ref=main"
    alias: server
  - name: maestro-agent
    version: "0.1.0"
    repository: "git+https://github.com/openshift-online/maestro@charts/maestro-agent?ref=main"
    alias: agent
    condition: agent.enabled
