apiVersion: v2
name: sentinel-nodepools
description: Sentinel deployment for nodepool lifecycle events
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: sentinel
    version: "0.1.0"
    repository: "git+https://github.com/openshift-hyperfleet/hyperfleet-sentinel@deployments/helm/sentinel?ref=main"
